public enum DataDirectoryIndex
{
  EXPORT_TABLE,
  IMPORT_TABLE,
  RESOURCE_TABLE,
  EXCEPTION_TABLE,
  CERTIFICATE_TABLE,
  BASE_RELOCATION_TABLE,
  DEBUG,
  ARCHITECTURE,
  GLOBAL_POINTER,
  TLS_TABLE,
  LOAD_CONFIG_TABLE,
  BOUND_IMPORT,
  IMPORT_ADDRESS_TABLE,
  DELAY_IMPORT_DESCRIPTOR,
  CLR_RUNTIME_HEADER
}
